---
title: "R Notebook"
editor_options: 
  chunk_output_type: inline
---

This is the final code framework to run my Elastic-Net
with Chained Equations procedure on Irish Monthly Rainfall data. This file is
specifically designed for running that procedure, and will not include any 
additional options. Look in the "rough work" folder I have for variants to 
this procedure or alternate procedures.

```{r}

## Initial Data Set up ##
rm(list = ls())

## Import General Use Functions ## 
source("tools.R")
source("regression.R")
source("interpolation.R")
source("interpolation_st.R")

## Import Required Libraries ##
import_everything()

```

```{r}

## Read in data (Rainfall from 1981-2010 with 30%, 50%, and 70% missingness) ##

# rain_70 <- read.csv("../data/70_perc_monthly_rain_1981-2010.csv",
#                     header = T, sep = ",")[-1]
# rain_50 <- read.csv("../data/50_perc_monthly_rain_1981-2010.csv",
#                     header = T, sep = ",")[-1]
# rain_30 <- read.csv("../data/30_perc_monthly_rain_1981-2010.csv",
#                     header = T, sep = ",")[-1]
# rain_15 <- read.csv("../data/15_perc_monthly_rain_1981-2010.csv",
#                     header = T, sep = ",")[-1]


## 27 stations in Dublin - for testing and debugging ##
rain_27 <- 
  read.csv("../../Rainfall/data/rain_27_stations.csv",
           header = T, sep = ",")[-c(1)]

cluster <- makeCluster(6)

```

```{r}

## Elastic-Net Procedure ##
## Take in observed and missing data, imputes all missing data ## 

impute_all <- function(data, newdata, response = "y", hyp_cycles = 2,
                       cycles = 5, init_values = F, init_method = "IDW", ...){
  
  # data            -observed data
  # newdata         -missing data to be imputed
  # response        -response variable (almost always y or qc_rain)
  # hyp_cycles      -number of cycles to fit hyper-parameters lambda and alpha
  # cycles          -number of total EM cycles to compute missing values
  # init_values     -this lets you check the initial starting values
  # init_method     -method for initial values (IDW (default), mean, or sample)
  
  
  ## Data formatting ##
  
  # Merge and order data
  df <- bind_rows(data, newdata)
  df <- df[order(df$stno, df$t), ]

  # Label missing data
  df$mis <- F
  df[is.na(df[response]), "mis"] <- T
  
  # Sort by number of missing values in each station, lowest to highest
  df <- df %>% group_by(stno) %>% mutate(n_mis = sum(mis)) %>% 
    arrange(n_mis) %>% dplyr::select(-c("n_mis"))
  
  # Save original data format
  df_old_format <- df %>% dplyr::select(-c(response))
 
  # If starting values needed for comparison to final values, they are saved
  if (init_values){
    starting_values <- df[(df$mis == T), ]
  }
  
  # Initially impute missing data with a simple method
  if (init_method == "IDW"){
    
    # Inverse Distance Weighting
    df[(df$mis == T), ] <- IDW_raw_ST(df[(df$mis == F), ], df[(df$mis == T), ],
                                      response = response, C = 15, nmax = 8,
                                      transformation = sqrt,
                                      reverse_transformation = 
                                        {function(x) x^2})
  }
  
  else if (init_method == "mean"){
    # Mean Imputation
    df <- df %>% group_by(stno) %>%
      mutate(across({{response}}, ~replace_na(., mean(., na.rm=TRUE))))
  }

  else if (init_method == "sample"){
      # Sample missing values from distribution 
    df <- df %>% group_by(stno) %>% 
      mutate({{response}} := 
               infill_lognorm_monthly(.data[[response]])) %>% ungroup()
  }
  
  else{
    warning("No valid initial imputation method given. Using default 
            (IDW) instead")
    # Inverse Distance Weighting
    df[(df$mis == T), ] <- IDW_raw_ST(df[(df$mis == F), ], df[(df$mis == T), ],
                                      response = response, C = 15, nmax = 8,
                                      transformation = sqrt,
                                      reverse_transformation = 
                                        {function(x) x^2})
  }
 
  # Square-Root Transformation of data
  df[response] <- sqrt(df[response])
  
  # Record positions of missing data (long table)
  mis_idx <- df %>% dplyr::select(t, stno, mis) %>%
    pivot_wider(names_from = "stno", values_from = "mis") %>%
    dplyr::select(-c("t")) %>% as.matrix()

  # Make wide table (stations are covariates)
  df <- df %>% dplyr::select(t, stno, {{response}}) %>%
    pivot_wider(names_from = "stno", values_from = response) %>%
    dplyr::select(-c("t"))
  
  # Add stno before each column name to avoid errors in formula
  colnames(mis_idx) <- paste0("stno", colnames(mis_idx))
  names(df) <- paste0("stno", names(df))
  
  # Initialise list of lambda and alpha values for each imputation model
  ls <- NA; as <- NA
  
  # Loop through imputation cycle multiple times
  for (i in 1:cycles){
    
    # Using RMSE between previous and current cycle as convergence criteria
    init_vals <- df[mis_idx]
    old_rmse <- ifelse(i == 1, mean(init_vals), new_rmse)
    
    # Impute data and update lambdas/alphas
    imp <- impute(df, mis_idx, ls, as)
    df <- imp$df
    ls <- imp$ls
    as <- imp$as
    
    # Check for convergence
    new_rmse <- rmse(init_vals, df[mis_idx])
    tol <- 1.25
    print(paste("Old:", old_rmse, "    New:", new_rmse))
    if (old_rmse / new_rmse < tol){
      break()
    }
    
    # Reset lambdas and alphas if in initial cycles
    if (i < hyp_cycles){
      ls <- NA; as <- NA
    }
    
    print(paste0("Cycle ", i, " completed"))
  }

  # Formatting dataframe back to original format
  names(df) <-substr(names(df), 5, nchar(names(df)))
  df <- pivot_longer(df, cols = everything(), 
                     names_to = "stno", values_to = response)
  df$stno <- as.numeric(df$stno)
  df <- df[order(df$stno), ]

  # Add time values back
  df$t <- rep(unique(df_old_format$t), length(unique(df$stno)))
  df <- left_join(df, df_old_format, by = c("stno", "t"))

  # Transform data back to original
  df[response] <- df[response] ^ 2
  
  # Return starting values if they were requested by "init_values"
  if (init_values){
    return(list("df" = df, "starting_values" = starting_values))
  }
  
  else{
    return(df)
  }
}




# One single imputation cycle for all stations

impute <- function(df, mis_idx, ls = NA, as = NA){
  
  # df              -Input data
  # mis_idx         -Index of all originally missing values
  # ls              -Initial lambda parameters for all imputation models
  # as              -Initial alpha parameters for all imputation models
  
  # Loop through each station
  for (count in 1:ncol(df)){
    
    # Get target station, other stations, and missing index
    newdata <- df[, count]; data <- df[, -count]
    mis_vals <- mis_idx[, count]
  
    # Impute target station
    imp <- imp_stn(data, newdata, mis_vals, ls[count], as[count])
    
    # Update data and hyper  parameters with imputation model output
    newdata <- imp$newdata; df[, count] <- newdata
    ls[count] <- imp$lambda; as[count] <- imp$alpha
    
    # if (count %% 30 == 0){
    #   print(count)
    # }
  }
  return(list("df" = df, "ls" = ls, "as" = as))
}




# Impute all missing values in a station using glmnet (Elastic-Net)

imp_stn <- function(data, newdata, mis_vals, lambda = NA, alpha = NA){
  
  # data                - Observed Stations (X)
  # newdata             - Target station (Y)
  # mis_vals            - Positions of missing values to be imputed
  # lambda              - Tuning Parameter
  # alpha               - Weighted value between lasso and ridge regression

  # Some stations might have no missing data
  if (any(mis_vals)){
    
    # Input data for glmnet
    x <- model.matrix(~ ., data)
    y <- unlist(newdata)
    ry <- unlist(mis_vals)
    
    # Lambda/alpha need to be fit if not provided
    if (is.na(lambda)){
      
      # Hyper parameters to be checked and fitted
      lambdas <- c(0.05, 0.1, 0.15, 0.2)
      alphas <- c(0.1, 0.35, 0.65, 0.9)

      # Fit E-Net with CV to fit lambda and alpha
      model <- cva.glmnet(x = x[!ry, ], y = y[!ry], 
                          lambda = lambdas, alpha = alphas,
                          outerParallel = cluster)
      
      # If you don't want to parallelize
      # model <- cva.glmnet(x = x[!ry, ], y = y[!ry],
      #                     lambda = lambdas, alpha = alphas)
      
      # The best cvm (error) and corresponding lambda for each alpha tested
      cvms <- unlist(lapply(model$modlist, extract_best_cvm))
      cvms <- matrix(cvms, ncol = 2, byrow = T)
      best_ls <- cvms[,1]; cvms <- cvms[,2]
      
      # Get alpha/lambda pair with lowest cvm
      alpha <- alphas[which(cvms == min(cvms))]
      lambda <- best_ls[which(cvms == min(cvms))]
    }
    
    else{
      model <- glmnet(x = x[!ry, ], y = y[!ry],
                      lambda = lambda, alpha = alpha)
    }
    
    # Calculate predicted values for missing data
    newdata[mis_vals, ] <- predict(model, x[ry,,drop=F], 
                                   s = lambda, alpha = alpha)
  }

  return(list("newdata" = newdata, "lambda" = lambda, "alpha" = alpha))
}




# Obtains lowest cvm and corresponding lambda from a `cvfit` object

extract_best_cvm <- function(cvfit){
  
  lambda <- cvfit$lambda.min
  cvm <- cvfit$cvm[which(cvfit$lambda == lambda)]
  
  return(c(lambda, cvm))
}




# Infill missing values with long-norm sampled variables plus monthly intercept
infill_lognorm_monthly <- function(x){
  
  # Note, matrix x should be seasonal every h=12 steps (months of a year)
  x <- sqrt(x)
  miss_x <- is.na(x)

  # Get monthly intercepts and fit normal distribution
  df <- data.frame(x, month = 1:12)
  df$month <- as.factor(df$month)
  model <- lm(x ~ month, data = df)
  fit <- fitdistr(model$residuals, "normal")

  # Sample missing values from distribution and add intercepts
  df[miss_x, "x"] <- rnorm(nrow(df[miss_x, ]), 
                           mean = fit$estimate[1], sd = fit$estimate[2])
  df[miss_x, "x"] <- df[miss_x, "x"] + predict(model, df[miss_x, ])
  
  x <- df$x ^ 2
  return(x)
}

```

```{r}

# Previous literature only runs CV on stations with no missing data (45 total)
# For consistency we'll do the same

# c_45 <- (rain_70 %>% group_by(stno) %>% 
#            summarise(no_missing = sum(is.na(qc_rain))) %>% 
#            filter(no_missing == 0))$stno

set.seed(222)

# st <- Sys.time()
# cv27 <- CV(rain_27,
#            impute_all, response = "qc_rain", LOOCV = F,
#            # check_by_final_year = T, nyears = 3, nstations = 20,
#            cycles = 16, hyp_cycles = 2, plot = T, get_results = T)
# 
# et <- Sys.time()
# print(et-st)
# 
# write.csv(cv27$df, "../../Rainfall/results/paper_2/rain_27/ENCE.csv")


df <- rain_27
data <- df[!is.na(df$qc_rain), ]
newdata <- df[is.na(df$qc_rain), ]

st <- Sys.time()
result_df <- impute_all(data, newdata, response = "qc_rain",
                        cycles = 16, hyp_cycles = 2)
print(Sys.time() - st)

```


```{r}

df <- rain_27

source("ENCE.R")

st <- Sys.time()

set.seed(222)
cv70 <- CV(df,
           impute_all, response = "qc_rain", LOOCV = F,
           cycles = 8, hyp_cycles = 2, 
           get_results = T)

et <- Sys.time()
print(et - st)

```



```{r}

set.seed(222)
cv70 <- CV(rain_70[rain_70$stno %in% c_45, ],
           impute_all, response = "qc_rain", LOOCV = F,
           
           check_by_year = T, check_by_year_var = "stno",
           extra_data = rain_70[!(rain_70$stno %in% c_45), ],
           
           cycles = 8, hyp_cycles = 2, get_results = T)
write.csv(cv70$df, "../results/CV_yearly/ENET_results_70.csv")



set.seed(222)
cv50 <- CV(rain_50[rain_50$stno %in% c_45, ],
           impute_all, response = "qc_rain", LOOCV = F,
           
           check_by_year = T, check_by_year_var = "stno",
           extra_data = rain_50[!(rain_50$stno %in% c_45), ],
           
           cycles = 8, hyp_cycles = 2, get_results = T)
write.csv(cv50$df, "../results/CV_yearly/ENET_results_50.csv")



set.seed(222)
cv30 <- CV(rain_30[rain_30$stno %in% c_45, ],
           impute_all, response = "qc_rain", LOOCV = F,
           
           check_by_year = T, check_by_year_var = "stno",
           extra_data = rain_30[!(rain_30$stno %in% c_45), ],
           
           cycles = 8, hyp_cycles = 2, get_results = T)
write.csv(cv30$df, "../results/CV_yearly/ENET_results_30.csv")



set.seed(222)
cv15 <- CV(rain_15[rain_15$stno %in% c_45, ],
           impute_all, response = "qc_rain", LOOCV = F,
           
           check_by_year = T, check_by_year_var = "stno",
           extra_data = rain_15[!(rain_15$stno %in% c_45), ],
           
           cycles = 8, hyp_cycles = 2, get_results = T)
write.csv(cv15$df, "../results/CV_yearly/ENET_results_15.csv")

```


```{r}

df <- read.csv("../results/CV_last_year/ENET_results_70.csv")
df1 <- read.csv("../results/CV_yearly/ENET_results_70_full_new.csv")

rmse(df$predicted_qc_rain, df1$predicted_qc_rain)

```


```{r}

# This code can by inserted into imp_stn() if you want to make station 
# selection plots during the ENCE

# ireland_dsn <- "../data/counties.json"
# ireland <- read_sf(dsn = ireland_dsn)
# 
# crs <- CRS("+init=epsg:29903")
# ireland <- st_transform(x = ireland, crs = crs)
# 
# sdf <- rain_50 %>% group_by(stno) %>% slice(1)
# coordinates(sdf) <- c("east", "north")
# proj4string(sdf) <- crs


#     m <- model$modlist[[which(alphas == alpha)]]
#     fit <- m$glmnet.fit
#     coefs <- fit$beta[, m$index[1]]
#     kept_stno <- names(coefs[coefs != 0])
#     target_stno <- colnames(newdata)[1]
#     kept_stno <- substr(kept_stno, 5, nchar(kept_stno))
#     target_stno <- substr(target_stno, 5, nchar(target_stno))
# 
#     sdf <- as.data.frame(sdf)
#     kept_sdf <- sdf[sdf$stno %in% kept_stno, ]
#     target_sdf <- sdf[sdf$stno == target_stno, ] 
#     removed_sdf <- sdf[(!(sdf$stno %in% kept_stno) & 
#                          !(sdf$stno == target_stno)), ] 
#     
#     
#     map_plot <- ggplot() +
#       
#       geom_sf(data = ireland, color="gray80", fill = "#a6fa93") +
#       
#       geom_point(removed_sdf, mapping = aes(x=east, y=north), size = 2, 
#                  shape = 24, fill = "#fcbe03", alpha = 0.3) +
#       geom_point(kept_sdf, mapping = aes(x=east, y=north), size = 2, 
#                  shape = 24, fill = "#fc0303") +
#       geom_point(target_sdf, mapping = aes(x=east, y=north), size = 3, 
#                  shape = 24, fill = "#00bfff") +
#       
#       theme(axis.title = element_blank(),
#         panel.background = element_rect(fill="#c4fff9")) 
# 
#     file_name <- paste0("../figures/em_plots/stno_", target_sdf$stno, ".png")
#     ggsave(file_name, plot = map_plot)
#     print(map_plot)

```

